
skillMetadata:
  sections:
    - name: Google-Authentication
        fields:
          - name: CalendarEmail
            type: email
            label: Enter your email address
            value:
          

